name: nginx-certbot

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    configs:
      - source: nginx.conf
        target: /etc/nginx/nginx.conf
    volumes:
      - sites-available:/etc/nginx/sites-available:ro 
      - sites-enabled:/etc/nginx/sites-enabled:ro 
      - conf.d:/etc/nginx/conf.d:ro 
      - ssl:/etc/nginx/ssl:ro 
      - acme-challenge:/var/www/html
      - letsencrypt:/etc/letsencrypt:ro 
    networks:
      - nginx-network
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
      - "host.docker.internal:host-gateway" # This allows the container to resolve "host.docker.internal" to the host's gateway.
    restart: unless-stopped
    healthcheck: 
      test: ["CMD", "service", "nginx" , "status" ]
      interval: 30s
      timeout: 3s 
      retries: 3 

  certbot:
    image: pavlosla/certbot:0.1
    container_name: certbot
    volumes:
      - letsencrypt:/etc/letsencrypt
      - acme-challenge:/var/www/html
    networks:
      - certbot
    restart: unless-stopped

volumes:
  sites-available:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/data/nginx/sites-available
    labels:
      xyz.laskaratos.nginx-certbot.description: "Sites available for nginx forwarding activation"
  sites-enabled:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/data/nginx/sites-enabled
    labels:
      xyz.laskaratos.nginx-certbot.description: "Sites enabled that nginx is forwarding"
  conf.d:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/data/nginx/conf.d
    labels:
      xyz.laskaratos.nginx-certbot.description: "Sites that nginx is forwarding"
  ssl:
    driver: local
    driver_opts:
      type: none
      o: bind 
      device: /srv/data/nginx/ssl
    labels:
      xyz.laskaratos.nginx-certbot.description: "SSL certificates for HTTPs authentation manually created"
  letsencrypt: 
    labels:
      xyz.laskaratos.nginx-certbot.description: "Letsencrypt SSL certificates obtained by certbot"
  acme-challenge:
    labels:
      xyz.laskaratos.nginx-certbot.description: "acme-challenge volume for domain name ownership"

configs:
  nginx.conf:
    file: /srv/configs/nginx/nginx.conf

networks:
  nginx-network:
    name: nginx-network
    attachable: true 
    driver: bridge
    labels:
      xyz.laskaratos.nginx-certbot.description: "Nginx cross container network container network"
  certbot:
    attachable: false
    driver: bridge
    labels:
      xyz.laskaratos.nginx-certbot.description: "Certbot private network"



